"""Adicionando categoria

Revision ID: 245b9dfdb998
Revises: 
Create Date: 2024-04-18 22:26:14.317503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '245b9dfdb998'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nome', sa.String(length=60), nullable=False),
    sa.Column('dta_cadastro', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('dta_atualizaca', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nome', sa.String(length=60), nullable=False),
    sa.Column('email_normalizado', sa.String(length=256), nullable=False),
    sa.Column('hash_password', sa.String(length=256), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email_normalizado'), 'usuarios', ['email_normalizado'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios_email_normalizado'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('categorias')
    # ### end Alembic commands ###
